plugins {
    id 'java'
    id 'com.google.protobuf' version '0.9.4' apply false
}

allprojects {
    group = 'ir.ebb'
    version = '0.0.1'

    repositories {
        maven {
            url "https://nexus.ebidar.net/repository/maven_ebidar/"
        }
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    dependencies {
        compileOnly libs.lombok
        annotationProcessor libs.lombok
        testImplementation libs.bundles.testBundle
    }

    tasks.named('test') {
        useJUnitPlatform()
    }

    tasks.register("prepareKotlinBuildScriptModel") {}
}
