package ir.ebb.wallet.wallet;

import ir.ebb.common.constant.enumeration.SettlementDelay;
import ir.ebb.wallet.constant.enumeration.WalletTransactionType;
import org.apache.pekko.actor.typed.ActorRef;

import java.util.UUID;

/**
 * Command protocol for the {@link WalletActor} sharded, event-sourced wallet entity.
 * Every command targets exactly one wallet, addressed by {@code accountNumber} (the shard
 * entity id).
 *
 * <p>Commands that need confirmation carry an {@code ActorRef<WalletReply>}.
 * {@link ChargeSeparCredit}, {@link SettleSeparCredit}, {@link ReconcileFromRayan} and
 * {@link SeedFromLegacy} are <em>fire-and-forget</em> (no reply-to): they are fanned out in
 * bulk by scheduled jobs / batch callers.
 *
 * <p>{@link WalletSerializable} marks these for Pekko Jackson JSON serialization.
 */
public sealed interface WalletCommand extends WalletSerializable {

    /** Admin: create an empty wallet for a user. {@code walletId} is generated by the caller. */
    record CreateWallet(long accountNumber, UUID walletId, ActorRef<WalletReply> replyTo) implements WalletCommand {}

    record Deposit(UUID trackingId, long accountNumber, long amount, SettlementDelay settlementDelay,
                   WalletTransactionType type, ActorRef<WalletReply> replyTo) implements WalletCommand {}

    record Withdraw(UUID trackingId, long accountNumber, long amount, SettlementDelay settlementDelay,
                     WalletTransactionType type, ActorRef<WalletReply> replyTo) implements WalletCommand {}

    record Freeze(UUID trackingId, long accountNumber, long amount, SettlementDelay settlementDelay,
                  WalletTransactionType type, boolean canSpendSeparCredit,
                  ActorRef<WalletReply> replyTo) implements WalletCommand {}

    record Unfreeze(UUID trackingId, long accountNumber, long amount, SettlementDelay settlementDelay,
                     WalletTransactionType type, ActorRef<WalletReply> replyTo) implements WalletCommand {}

    record Spend(UUID trackingId, long accountNumber, long amount, SettlementDelay settlementDelay,
                  WalletTransactionType type, ActorRef<WalletReply> replyTo) implements WalletCommand {}

    /** Freeze on T+0 without spending credit (equivalent to {@code Freeze} with T_PLUS_0, {@code canSpendSeparCredit=false}). */
    record FreezeForT0(UUID trackingId, long accountNumber, long amount,
                        WalletTransactionType type, ActorRef<WalletReply> replyTo) implements WalletCommand {}

    /** Spend previously-frozen T+0 funds. */
    record SpendT0(UUID trackingId, long accountNumber, long amount,
                    WalletTransactionType type, ActorRef<WalletReply> replyTo) implements WalletCommand {}

    /** Set a new credit ceiling (admin). */
    record AddCredit(UUID trackingId, long accountNumber, long creditAmount,
                      ActorRef<WalletReply> replyTo) implements WalletCommand {}

    /** Read: return the authoritative current state (no persistence). */
    record GetWallet(ActorRef<WalletReply> replyTo) implements WalletCommand {}

    /** Read: compute buying power for a settlement tier from the current state (no persistence). */
    record GetBuyingPower(SettlementDelay settlementDelay, ActorRef<WalletReply> replyTo) implements WalletCommand {}

    /** Fire-and-forget: charge (loan=true) or decrease (loan=false) separ credit. */
    record ChargeSeparCredit(long accountNumber, long amount, boolean isLoan) implements WalletCommand {}

    /** Fire-and-forget: settle separ credit (separCredit -= separInitialCredit; separInitialCredit = 0). */
    record SettleSeparCredit(long accountNumber) implements WalletCommand {}

    /** Fire-and-forget: reconcile the wallet from the authoritative Rayan snapshot; {@code target} is the
     *  desired state (id/user/accountNumber preserved by the caller; credit fields replaced from Rayan). */
    record ReconcileFromRayan(WalletState target) implements WalletCommand {}

    /** Fire-and-forget one-off migration: seed an entity's initial state from the legacy {@code wallet} row. Idempotent. */
    record SeedFromLegacy(WalletState state) implements WalletCommand {}
}
