plugins {
    id 'java-library'
}

dependencies {
    api project(':base')

    api libs.bundles.pekkoBundle
    api libs.bundles.pekkoClusterBundle
    api libs.bundles.pekkoPersistenceBundle
    api libs.bundles.pekkoProjectionBundle
    api libs.apacheCommons
    api libs.uuidCreator
    api libs.vavr
    api libs.fastjson2

    api libs.postgres
    api libs.r2dbcPostgres
    api libs.hikari
    api libs.liquibase
    api libs.kafkaClients

    implementation libs.protobuf

    testImplementation libs.pekkoPersistenceTestkit
}
